### ISSUE TITLE
Integrating your function in another module

### ISSUE THREAD

**Issue by lrq3000** [bfontaine/flatkeys#3]
Hello there,

Thank you for your module, it is very useful!

I integrated it into my project of flattened dict for out-of-core computing:

https://github.com/lrq3000/fdict

I know this is not the best standard, but is it ok for you to have your function integrated in my module? I would like to avoid any third-party dependency, which is the case now, except for your function, so I integrated it into my `fdict` class.

Also if you are interested to try out the `fdict` or `sfdict` module, feel free to feedback so I can enhance :-)

**Comment by bfontaine** [comment]
Yes it’s perfectly fine! 😄

**Comment by lrq3000** [comment]
Thanks a lot @bfontaine! :-D
